{% set name = "pytest-filter-subpackage" %}
{% set version = "0.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 3f468f1b36518128869b95deab661ba45ed6293854329fef14da4c8cac78af56

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - setuptools_scm
    - python
    - setuptools
    - wheel
  run:
    - python
    - pytest >=4.6
    - packaging

test:
  source_files:
    - tests/
  requires:
    - pytest
    - pip
  imports:
    - pytest_filter_subpackage
  commands:
    - pip check
    - pytest tests -vv -k "not(test_with_rst or test_flag_single_subpackage_with_rst or test_flag_multiple_subpackage_with_rst)"

about:
  home: https://github.com/astropy/pytest-filter-subpackage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: "Pytest plugin for filtering based on sub-packages"
  description: |
    This package contains a simple plugin for the pytest framework that
    provides a shortcut to testing all code and documentation for a given
    sub-package.
  doc_url: https://github.com/astropy/pytest-filter-subpackage/blob/master/README.rst
  dev_url: https://github.com/astropy/pytest-filter-subpackage

extra:
  recipe-maintainers:
    - mwcraig
    - astrofrog-conda-forge
